title: Application Shimming
description: Detects application shimming through sdbinst or registry modification.
author: keyboardcrunch
date: 10/10/2020
modified: null
mitre:
   tactic: Privilege Escalation, Persistence
   technique: T1546
   subtechnique: 008
operating_system: windows
query: filter
  (
    src.process.name == "sdbinst.exe" &&
    process.command_line contains ".sdb"
  )
  ||
  (
    (
      registry.keyPath contains "AppInit_DLLs" ||
      registry.path contains "AppCompatFlags"
    )
    &&
    (
      event.type == "Registry Value Create" ||
      event.type == "Registry Value Modified"
    )
  )
false_positives: null
tags: null
